# Setup
title:        DokuWeaki
tagline:      A (Doku)Wiki for Agile Software Development
baseurl:      ""

# About/contact
author:
  name:       Henrique Ferrolho
  url:        http://ferrolho.github.io/

# DokuWeaki
bundle-download-link: https://github.com/dokuweaki/dokuweaki.github.io/blob/master/assets/dokuweaki.zip?raw=true

# Gems
gems:
  - jemoji

#Others
markdown: kramdown
