# Setup
title:        DokuWeaki
tagline:      A (Doku)Wiki for Agile Software Development
baseurl:      ""

# About/contact
author:
  name:       Henrique Ferrolho
  url:        http://ferrolho.github.io/

# DokuWeaki
bundle-download-link: https://github.com/softeng-feup/dokuweaki/raw/development/dokuweaki-bundle.zip

# Gems
gems:
  - jemoji

#Others
markdown: kramdown
